= MicroProfile Config
:experimental: true
:product-name: MicroProfile Config

This cheat sheet covers the basics of MicroProfile Config specification uses.

== Injecting configuration properties

Inject a simple ConfigProperty

[source,java]
----
@Inject
@ConfigProperty(name = "my.custom.message")
String customMessage;
----

Inject a ConfigProperty with a default value

[source,java]
----
@Inject
@ConfigProperty(name = "my.custom.message", defaultValue="My message")
String customMessage;
----

.Required values if no default value is provided
****
`base_type`:: exception during deployment
`Optional<base_type>`:: results in `Optional.empty()`
`Provider<base_type>`:: deployment exception but the value is reloaded with every access
****

== Using injected configuration object

[source,java]
----
@Inject
Config config;
----
`getValue(String, Class<T>)`:: get single value with specified type
`getOptionalValue(String, Class<T>)`:: get value as optional
`getPropertyNames()`:: get iterable with names of all found properties
`getConfigSources()`:: get all config sources

NOTE: there is also an option for programatic lookup with `ConfigProvider.getConfig()`

== Config sources

=== Default config sources

`System properties`:: ordinal 400
`Environment properties`:: ordinal 300
`META-INF/microprofile-config.properties`:: ordinal 100

=== Custom config sources

Implementations of `org.eclipse.microprofile.config.spi.ConfigSource`::
registration in `/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource`

Implementations of `org.eclipse.microprofile.config.spi.ConfigSourceProvider`::
registration in `/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider`

== Converters

=== Default converters

`Boolean`, `Byte`, `Short`, `Integer`, `Long`, `Float`, `Double`, `Character`, `Class`::
in both boxed and unboxed variants

`array`, `List`, `Set`::
parameterized by the base types

=== Custom converters

implementations of `org.eclipse.microprofile.config.spi.Converter`::
registration in `/META-INF/services/org.eclipse.microprofile.config.spi.Converter`

